Update README.md
ezod/flipperzero-gps pull request #26
Opened 2024-01-11 23:41 UTC by haisenteck

Add to list Fastrax UP500 Module

2024-01-27 21:03 UTC, haisenteck commented
fixes for UART REFACTOR in the other 3 commit.

2024-02-11 04:37 UTC, kickercompkid commented
Also please add mRo GPS u-Blox Neo-M8N / 3DR module verified.
https://store.mrobotics.io/product-p/m10034-solo.htm

2024-02-15 04:51 UTC, ezod requested changes
Thanks for this, especially addressing the new UART stuff! This PR includes a variety of unrelated changes; most are reasonable but require minor changes. See comments/suggestions.

2024-02-15 04:51 UTC, ezod commented on README.md
> +* Fastrax UP500
Ideally, move this up for alphabetical order.

2024-02-15 04:51 UTC, ezod commented on gps.c
> +            snprintf(buffer, 64, "%.2f Km/h", (double)(gps_uart->status.speed * KNOTS_TO_KPH));
You aren't the first to suggest this so I'll accept it, but I'd rather use `kph` and `mph` in lowercase to save horizontal space.

```suggestion
            snprintf(buffer, 64, "%.2f kph", (double)(gps_uart->status.speed * KNOTS_TO_KPH));
```

2024-02-15 04:51 UTC, ezod commented on gps.c
> +            snprintf(buffer, 64, "%.2f Mi/h", (double)(gps_uart->status.speed * KNOTS_TO_MPH));
```suggestion
            snprintf(buffer, 64, "%.2f mph", (double)(gps_uart->status.speed * KNOTS_TO_MPH));
```

2024-02-15 04:51 UTC, ezod commented on gps.c
> +            snprintf(buffer, 64, "%.2f Kn", (double)gps_uart->status.speed);
```suggestion
            snprintf(buffer, 64, "%.2f kn", (double)gps_uart->status.speed);
```

2024-02-15 04:51 UTC, ezod commented on gps.c
> +
It looks like this was changed a while back among other things to include the delay inside `furi_hal_power_enable_otg()`: https://github.com/flipperdevices/flipperzero-firmware/pull/2842

```suggestion
    bool otg_was_enabled = furi_hal_power_is_otg_enabled();
    uint8_t attempts = 5;
    while(--attempts > 0) {
        if(furi_hal_power_enable_otg()) break;
    }
    if(attempts == 0) {
        if(furi_hal_power_get_usb_voltage() < 4.5f) {
            FURI_LOG_E(
                TAG,
                "Error power otg enable. BQ2589 check otg fault = %d",
                furi_hal_power_check_otg_fault() ? 1 : 0);
        }

```

2024-02-15 04:51 UTC, ezod commented on gps_uart.c
> +	if(ev == FuriHalSerialRxEventData) {
```suggestion
    GpsUart* gps_uart = (GpsUart*)context;
	
    if(ev == FuriHalSerialRxEventData) {
```

2024-02-15 04:51 UTC, ezod commented on gps_uart.c
> +	furi_hal_serial_init(gps_uart->serial_handle, gps_uart->baudrate);
```suggestion
    furi_assert(gps_uart->serial_handle);
    furi_hal_serial_init(gps_uart->serial_handle, gps_uart->baudrate);
```

2024-02-15 04:51 UTC, ezod commented on gps_uart.c
> +    gps_uart->speed_units = KPH;
I think it makes more sense to keep the native unit from the NMEA message as the default?

```suggestion
    gps_uart->speed_units = KNOTS;
```

2024-02-15 04:51 UTC, ezod commented on gps_uart.h
> +	FuriHalSerialHandle* serial_handle;
```suggestion
    FuriHalSerialHandle* serial_handle;
```

2024-02-15 04:51 UTC, ezod commented on gps_uart.c
> +void gps_uart_serial_init(GpsUart* gps_uart) {
Is there a reason I'm missing for removing `static` here?

```suggestion
static void gps_uart_serial_init(GpsUart* gps_uart) {
```

2024-02-15 04:51 UTC, ezod commented on gps_uart.c
> +#include "minmea.h"
Can you explain the reasoning here? `minmea.h` is provided via `fap_private_libs` and the submodule under `lib`, so my understanding is it should be included by search path with `<>`. As far as I can tell changing to quotes should have no effect.

```suggestion
#include <minmea.h>
```

2024-02-26 15:47 UTC, ezod approved these changes

2024-02-26 15:51 UTC, ezod commented on gps.c
> +                TAG,
```suggestion
                "GPS",
```

2024-02-26 15:53 UTC, ezod commented on gps.c
> +
```suggestion
    }

```

2024-02-26 17:14 UTC, merged